const char *gfx_source =
""
""
"\n#version 130\n"
""
"out vec4 gl_FragColor;"
""
"const vec2 H=vec2 (1920,1080);"
"const float d1=9.;"
""
"const float R1=acos(-1.);"
"const vec3 c=vec3 (1.,0.,-1.);"
"const float v=.45,"
"h1=7.,"
"Z=-.01;"
""
"void i1(in vec3 r,out float i)"
"{"
"r=fract(r*.1031);"
"r+=dot(r,r.yzx+33.33);"
"i=fract((r.x+r.y)*r.z);"
"}"
""
"void A1(in vec2 u1,out float i)"
"{"
"vec3 r=fract(vec3 (u1.xyx)*.1031);"
"r+=dot(r,r.yzx+33.33);"
"i=fract((r.x+r.y)*r.z);"
"}"
""
"void I(in vec3 o,in vec3 A,out float i)"
"{"
"vec3 b=abs(o)-A;"
"i=length(max(b,0.0))"
"+min(max(b.x,max(b.y,b.z)),0.0);"
"}"
""
"void e1(in vec3 o,in vec3 A,in float W,out float i)"
"{"
"I(o,A,i);"
""
"float b;"
"I(o,A+c.zzx*W,b);"
"i=max(i,-b);"
"I(o,A+c.xzz*W,b);"
"i=max(i,-b);"
"I(o,A+c.zxz*W,b);"
"i=max(i,-b);"
"}"
""
"void N1(in float z1,in float v1,in float y1,out float i)"
"{"
"vec2 D=vec2 (v1,abs(z1)-0.5*y1);"
"i=min(max(D.x,D.y),0.0)+length(max(D,0.0));"
"}"
""
"void L(in vec2 F,in vec2 k,out vec2 m)"
"{"
"m=(F.x<k.x)?F:k;"
"}"
""
"void C1(in vec2 F,in vec2 k,out vec2 m)"
"{"
"m=(F.x>k.x)?abs(F):abs(k)*c.zx;"
"}"
""
"float g1(in float i)"
"{"
"return smoothstep(1.5/H.y,-1.5/H.y,i);"
"}"
""
"void N(in vec3 o,out vec2 m)"
"{"
"float i,"
"f=v,"
"s;"
""
"m=vec2 (o.z+v-Z,0.);"
""
"for(float l=0.;l<h1;l+=1.)"
"{"
"vec3 w=mod(o,f*c.xxx)-.5*f,"
"C=(o-w)/f*2.;"
"if(max(abs(C.x),abs(C.y))>pow(2.,l+1.))"
"break;"
"i1(1.e2*C-100.*l,s);"
"if(s>.4)"
"{"
"e1(w,(.5*s-.05*l)*f*c.xxx,(.2-.01*l)*(.5*s-.05*l)*f,i);"
"s=2.*(s-.5);"
"if(s<.5)L(m,vec2 (i,1.),m);"
"else L(m,vec2 (i,-1.),m);"
"}else break;"
"if(s>.6)"
"{"
"I(w,(.45*s-.05*l)*f*c.xxx,i);"
"s=2.5*(s-.6);"
"L(m,vec2 (i,2.+floor(3.*s)),m);"
"}"
"f/=2.;"
"}"
"vec3 C=vec3 (-1.,-1.,-1.);"
"i1(1.e2*C,s);"
"e1(o-.5*C*v,.525*s*v*c.xxx,.28*.5*s*v,i);"
"L(m,vec2 (i,1.),m);"
"}"
""
"\n#define b1(n,p)void n(in vec3 o,out vec3 d,in float M){vec2 a,g;p(o,a);p(o+M*c.xyy,g);d.x=g.x;p(o+M*c.yxy,g);d.y=g.x;p(o+M*c.yyx,g);d.z=g.x;d=normalize(d-a.x);}\n"
"b1(X,N)"
""
"\n#define o1(m1,f1,r1,step)void m1(out vec3 o,in vec3 n,inout float i,in vec3 x,in int h,out int l,out vec2 a){for(l=0;l<h;++l){o=n+i*x;f1(o,a);if(a.x<1.e-4)return ;if(r1){l=h;}i+=step;}}\n"
"o1(Q,N,max(max(abs(o.x),abs(o.y)),abs(o.z))>1.1*v,min(a.x,5.e-4))"
"o1(w1,N,o.z>.5,min(a.x,1.e-2))"
""
"void V(in vec3 n,in vec3 x,in vec3 f,out float i)"
"{"
"vec3 u=min((f-n)/x,(-f-n)/x);vec2 t1=abs(n.yz+u.x*x.yz),"
"s1=abs(n.xz+u.y*x.xz),"
"n1=abs(n.xy+u.z*x.xy);"
"vec4 y=100.*c.xyyy;"
""
"y=mix(y,vec4 (u.x,c.xyy),float (all(lessThan(t1,f.yz)))*step(u.x,y.x));"
"y=mix(y,vec4 (u.y,c.yxy),float (all(lessThan(s1,f.xz)))*step(u.y,y.x));"
"y=mix(y,vec4 (u.z,c.yyx),float (all(lessThan(n1,f.xy)))*step(u.z,y.x));"
""
"i=y.r;"
"}"
""
"void P(in vec3 o,in vec3 d,in vec3 x,in vec3 t,inout vec3 e,in vec2 a)"
"{"
"if(a.y==-1.){"
"e=vec3 (0.09,0.09,0.09);"
"e=.6*e"
"+.8*e*max(dot(t-o,d),0.)"
"+1.5*e*pow(max(dot(reflect(t-o,d),x),0.),2.);"
"}"
"else if(a.y==0.){"
"e=.1*c.xxx;"
"e=.1*e"
"+.8*e*max(dot(t-o,d),0.)"
"+.5*e*pow(max(dot(reflect(t-o,d),x),0.),2.);"
"}"
"else if(a.y==1.){"
"e=.4*c.xxx;"
"e=.6*e"
"+.8*e*max(dot(t-o,d),0.)"
"+1.5*e*pow(max(dot(reflect(t-o,d),x),0.),2.);"
"}"
"else if(a.y==2.){"
"e=vec3 (1.00,0.29,0.24);"
"e=.7*e"
"+.8*e*max(dot(t-o,d),0.)"
"+.5*e*pow(max(dot(reflect(t-o,d),x),0.),2.);"
"}"
"else if(a.y==3.){"
"e=vec3 (0.33,0.86,0.10);"
"e=.7*e"
"+.8*e*max(dot(t-o,d),0.)"
"+.5*e*pow(max(dot(reflect(t-o,d),x),0.),2.);"
"}"
"else if(a.y==4.){"
"e=vec3 (1.00,0.59,0.12);"
"e=.7*e"
"+.8*e*max(dot(t-o,d),0.)"
"+.5*e*pow(max(dot(reflect(t-o,d),x),0.),2.);"
"}"
"}"
""
"void l1(out vec4 x1,in vec2 c1)"
"{"
"vec2 B=(c1-.5*H.xy)/H.y,"
"a,p1,"
"q;"
"vec3 e=c.yyy,"
"n=2.*c.zzx-.4*c.yyx+.05*c.zzy,"
"O=n,"
"s=c.xzy,"
"p=c.yyy,"
"a1=cross(normalize(p-n),-s),"
"x,"
"d,"
"o,"
"z=c.yyy,"
"t,"
"Y,"
"T,"
"S,"
"J,"
"j;"
"int h=1500,"
"l;"
"float i=0.,E;"
""
"p+=B.x*s+B.y*a1;"
"x=normalize(p-n);"
""
"V(n,x,v*c.xxx,i);"
"if(i>1.e1)"
"{"
"i=-(n.z+v-Z)/x.z;"
"o=n+i*x;"
"N(o,a);"
"}"
"Q(o,n,i,x,h,l,a);"
""
"t=c.xzx;"
"Y=c.zxx;"
""
"if(l<h)"
"{"
"X(o,d,5.e-5);"
"d=round(d);"
"}"
"else "
"{"
"i=-(n.z+v-Z)/x.z;"
"o=n+i*x;"
"N(o,a);"
"X(o,d,5.e-5);"
"d=round(d);"
"}"
""
"P(o,d,x,t,e,a);"
"P(o,d,x,Y,z,a);"
"e=mix(e,z,.5);"
""
"if(a.y==0.)"
"{"
"O=o;"
"T=reflect(x,d);"
"E=.01;"
"V(O,T,v*c.xxx,E);"
"Q(S,O,E,T,h,l,q);"
""
"if(l<h)"
"{"
"X(S,j,5.e-4);"
"d=round(d);"
"P(S,j,T,t,z,q);"
"P(S,j,T,Y,J,q);"
"z=mix(z,J,.5);"
"e=mix(e,z,.1);"
"}"
"}"
""
""
""
""
""
"S=o;"
""
"n=o;"
"x=normalize(t-o);"
"i=1.e-2;"
""
"{"
"float G=1.0;"
"float K=1.e20;"
"for(int l=0;l<h;++l)"
"{"
"o=n+i*x;"
"N(o,a);"
"if(a.x<1.e-4)"
"{"
"G=0.;"
"break;"
"}"
"if(o.z>.5)break;"
"float w=a.x*a.x/(2.0*K);"
"float b=sqrt(a.x*a.x-w*w);"
"G=min(G,100.0*b/max(0.0,i-w));"
"K=a.x;"
"i+=min(a.x,5.e-3);"
"}"
"e=mix(.3*e,e,G);"
"}"
""
""
"e=e+1.*e*e*e;"
""
"x1=vec4 (clamp(e,0.,1.),1.);"
"}"
""
"void main()"
"{"
"vec4 e=vec4 (0.);"
"float R=sqrt(d1)-1.;"
"for(float l=-.5*R;l<=.5*R;l+=1.)"
"for(float U=-.5*R;U<=.5*R;U+=1.)"
"{"
"vec4 z;"
"l1(z,gl_FragCoord.xy+vec2 (l,U)*1./max(R,1.));"
"e+=z;"
"}"
"e/=d1;"
"gl_FragColor=e;"
"}"
""
;
